"""add_unique_constraints

Revision ID: a96a6124e721
Revises: 1a2d48c92870
Create Date: 2025-12-07 13:12:29.180015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96a6124e721'
down_revision: Union[str, None] = '1a2d48c92870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_permission_board_user', 'permission', ['board_id', 'user_id'])
    op.create_unique_constraint('uq_task_member_task_user', 'task_members', ['task_id', 'user_id'])
    op.create_unique_constraint('uq_team_member_team_user', 'team_member', ['team_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_member_team_user', 'team_member', type_='unique')
    op.drop_constraint('uq_task_member_task_user', 'task_members', type_='unique')
    op.drop_constraint('uq_permission_board_user', 'permission', type_='unique')
    # ### end Alembic commands ###
