"""remove pgoto and password_hash column from user model

Revision ID: 9ebcf4928f8d
Revises: 2ce5b3d4e395
Create Date: 2025-11-26 00:35:31.836669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ebcf4928f8d'
down_revision: Union[str, None] = '2ce5b3d4e395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'color')
    op.drop_column('user', 'photo')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('board', sa.Column('color', postgresql.ENUM('GREEN', 'BLACK', 'WHITE', 'BLUE', 'RED', 'YELLOW', 'ORANGE', 'BROWN', 'PURPLE', name='boardcolor'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
